### ISSUE TITLE
IAM mismatch between SAM gui and pysam

### ISSUE THREAD

**Issue by fgro** [NREL/pysam#12]
Dear all,

I am struggling to make "subarray1_aoi_modifier" agree between SAM gui pysam although:
* subarray1_axisrotation
* dn
* df
* gh/gh_calc
* airmass 
agree!
I use 'blythe_ca_33.617773_-114.588261_psmv3_60_tmy.csv' and a single axis tracker.

**Comment by fgro** [comment]
Already 'subarray1_poa_eff_diff' is a few W/m² higher for pysam than SAM.

**Comment by fgro** [comment]
I had a different "constant diffuse sky shading loss" under.

**Comment by dguittet** [comment]
Hi fgro, thanks for your comment. 

Depending on which PySAM and SAM GUI versions you're using, the values may not match up since I think there were some changes to the aoi modifier code recently.

However, I'm using the beta 2020.1.14 and PySAM 2.0.2, and finding agreement using the Photovoltaic, No financial ("FlatPlatePVNone" ) configuration with blythe resource data.

**Comment by dguittet** [comment]
Closing due to lack of additional issues
