### ISSUE TITLE
Problems installing NREL-PySAM for Python 3.11 on windows 10

### ISSUE THREAD

**Issue by anaalvarezmari** [NREL/pysam#137]
Hi,

I am trying to install NREL-PySAM  in Python 3.11 from the command prompt and I get the error reproduced below. What am I doing wrong ? Are there any prior steps I should have taken?

Thanks in advance.
Ana

------------------------
****C:\Users\ST634JT>pip install NREL-PySAM
Collecting NREL-PySAM
  Using cached NREL-PySAM-2.1.1.tar.gz (790 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ST634JT\AppData\Local\Temp\pip-install-s1k_2n2o\nrel-pysam_090ec1cc38934386b94b25fc59fbe99a\setup.py", line 24, in <module>
          defaults_dir = os.environ['SAMNTDIR']+"/api/api_autogen/library/defaults/"
                         ~~~~~~~~~~^^^^^^^^^^^^
        File "<frozen os>", line 679, in __getitem__
      KeyError: 'SAMNTDIR'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed**

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.**

-------------------

**Comment by cpaulgilman** [comment]
Hi Ana,

PySAM works with Python 3.6 to Python 3.10. We do not yet have support for Python 3.11. You can see the complete list of PySAM versions in the [Python Package Index (PyPI)](https://pypi.org/project/NREL-PySAM/#files).

The message about the SAMNTDIR environment variable suggests that you are trying to build PySAM from source. If that is the case, you can find build instructions in the [PySAM repository's wiki](https://github.com/NREL/pysam/wiki/Building,-Packaging-and-Distributing). 

Otherwise, to install the PySAM package without building from source, see the [installation instructions](https://nrel-pysam.readthedocs.io/en/master/installation.html) in the PySAM documentation (it also mentions the Python versions PySAM works with).

If you need help with installing, building, or using PySAM, please post your questions on the [PySAM forum](https://sam.nrel.gov/forum/forum-sdk.html). We use the Issues here for bug reporting and feature requests.

Best regards,
Paul.
