### ISSUE TITLE
ssc_data_t values cannot be assigned with an uppercase variable name

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/pysam#19]
The following works fine:
data.P_ref = ${P_ref};     // in UI form Equations window in MSPT System Design
vt_get_number(vt, "P_ref", &P_ref);     // in cmod_csp_tower_eqns.cpp

This does not work:
vt->assign("Q_rec_des", Q_rec_des);     // in cmod_csp_tower_eqns.cpp
${Q_rec_des} = data.Q_rec_des;     // in UI form Equations window in MSPT System Design

This works:
vt->assign("q_rec_des", Q_rec_des);     // in cmod_csp_tower_eqns.cpp
${Q_rec_des} = data.q_rec_des;     // in UI form Equations window in MSPT System Design

**Comment by dguittet** [comment]
@sjanzou 

Everything stored in var_table gets changed to lower case. When you look up as in `vt_get_number`, the lower case name is searched, so that's why #1 works and why #3 works.

Recently, I added the `vt->assign_match_case()` and `vt->lookup_match_case()` functions but these are not used in UI forms.

In a soon-to-be-merged branch, I changed the behavior of `vt->lookup` to check for case-matching first, then lowercase: https://github.com/NREL/ssc/commit/f8f975fb2bd7281247ec0e54d7e3d2edf8a5490a#diff-f8a2cb798c1d1f44cd62b1eb2a16c701

Then for #2 if you did `vt->assign_match_case()` then `${Q_rec_des} = data.Q_rec_des` it should work.

But this is needlessly confusing... I think it's inconsistent for ssc_data_t values to not support upper case names but for LK data and SAM data types to do so.

**Comment by dguittet** [comment]
closing this since it's not a PySAM-specific issue
