### ISSUE TITLE
SAM and PySAM don't agree?

### ISSUE THREAD

**Issue by frohro** [NREL/pysam#21]
I probably don't understand what I'm doing, but it seems to me that the 2020.1.17 beta is not giving me the same results when I import the .json data from SAM as SAM gives me.

What I did was to export my pvwatts7 simulation from SAM, and I tried to import it following the example.  It seems to run okay, and some values especially from PWwatts7 agree, but some, especially the financial model do not agree.  

I'm enclosing a .zip with the .json and the .py files.  You will need Tkinter installed to pick the files, or modify the source code if you like.  

I'm just trying to make sure I understand what I'm doing by trying to duplicate what SAM is telling me before I try running my calculations to calculate npv and payback period for a changing electricity price.

Any help would be appreciated.  And my apologies if I'm just doing something stupid.  It is kind of likely.  :-)

[Example_Problem.zip](https://github.com/NREL/pysam/files/4223367/Example_Problem.zip)

**Comment by frohro** [comment]
I should have included the .sam file.
[PySAM_tests.zip](https://github.com/NREL/pysam/files/4223386/PySAM_tests.zip)
So here it is.

**Comment by dguittet** [comment]
Hi @frohro thanks for the question, I'm glad you're digging into the models :)

I think the issue is you're comparing the Single owner to a Commercial financial configuration. In order to reproduce the Commercial configuration, you'll need to string together the Utilityrate5 with the Cashloan module instead of Singleowner.

**Comment by frohro** [comment]
You are right.  I somehow thought that since there was a single owner that Single owner applied.  Thanks for the clarification.  I did try to model the correct chain on the one that seemed to work with single owner, but I get a segmentation fault when I do that.  I'm enclosing my attempt here.  

After I get done with this, I'll do what I can to help you make it easier for others following in my path.  It looks like the file to modify is: [Import.html](https://github.com/NREL/pysam/blob/master/docs/_build/html/Import.html)
Feel free to use my feeble attempts at using PySAM as examples for others of what to do and what not to do.  :-)
Thanks for the help Darice!

[LEAC.zip](https://github.com/NREL/pysam/files/4227923/LEAC.zip)

**Comment by frohro** [comment]
I looked a little closer, and it looks like the file to modify is [Import.rst](https://github.com/NREL/pysam/blob/master/docs/Import.rst).

**Comment by frohro** [comment]
So I think I have something "working," but it is still giving me different answers than the SAM simulation, and they seem to be based on getting a different amount of generated power in the initial PVWatts simulation.
[PySAM_tests1.zip](https://github.com/NREL/pysam/files/4229073/PySAM_tests1.zip)
It almost looks like there were some minor model changes somewhere, but I don't know. 
Thanks for all your help!
Rob

**Comment by frohro** [comment]
I'm assuming there is some small change in the model and working on toward my goal of allowing a variable electric rate.  I am able to print(pv.Lifetime.analysis_period), but when I try print(pv.Lifetime.dc_degradation) I get: 

![dc_degradation](https://user-images.githubusercontent.com/994565/74928965-4321cb00-5426-11ea-95b2-d2d19add415f.png)
I see it in the json file.  It is obviously being used in the pvwatts calculations, but I can't seem to use that variable, and I need to.  :-)  Help!

**Comment by frohro** [comment]
Another clue to the dc_degradation problem is that the .json file has for analysis_period:
"analysis_period" : 25,
but for dc_dgradadion it doesn't have the "dc" part.
"degradation" : [ 0.5 ],
so the bug may be in the code in SAM for writing the .json file.

**Comment by frohro** [comment]
Editing the .json file to add "dc_" to degradation didn't change anything I could detect.  It still claims "dc_degradation not assigned".

**Comment by frohro** [comment]
Hi Darice,
I've been tasked to do a solar study here on Guam, and part of that study is to make sure software is setup and understood by those I'm leaving behind in three weeks.  My plan is to finish creating this python script that incorporates a changing electric rate over time.  For a while it was looking like the best case wouldn't really be feasible, so I could just use the SAM GUI, but now it is evident that even though it gets less  feasible as a function of time, it should be feasible for the next few years.  I need to produce a persuasive and updatable report that shows that.  I also need to make some tutorial things so the guys here can run SAM and know how to use SAM in concert with PySAM.  I believe in open source software and might even get some professional development credit by writing the tutorials for SAM with PySAM if they can be of use to you and NREL too.  I want to try to achieve all these goals.  If you have ideas how you would prefer me to do this so it fits in with your documentation the best, please let me know.  This probably isn't the best place to do that discussion, but I know you are reading this, and it is related in a tangential way, so I'm starting here.

Thanks,
Rob

**Comment by dguittet** [comment]
@frohro Apologies for delayed response! 

Yes there were several changes to Pvwattsv7 versus v5. You can see them listed here: https://nrel.github.io/SAM/doc/releasenotes.html

I'm not seeing `dc_degradation` in 100kW_PVWatts.json which means it hasn't been assigned. This is very unintuitive but there are several "degradation" variables and `dc_degradation` is applied to PVwatts before the inversion to AC and is applied over the lifetime. 

We haven't officially exposed lifetime simulations for PVWatts in the SAM GUI (for several reason, if you're interested, I can let you know) so that's why `dc_degradation` isn't produced in the json.

You will have to set it yourself prior to simulation as

`pv.Lifetime.dc_degradation = x`

Where x can be either a single number which will be compounded over the years or as a time series for the entire lifetime.

**Comment by dguittet** [comment]
Regarding your last point about your solar study and tutorials, I'm definitely interested and think they would be broadly useful! Some of the questions you've come up with have been echoed elsewhere, but I haven't had enough time to invest in documentation (even though it is a major factor, I think, to the success of open-source software!), so your help would be appreciated.

I think additions to the readthedocs would be the best, and sample code is always helpful. We also do a variety of documentation and tutorials for SAM, so that's another venue. 

I'm going to discuss this with the team broadly and get back to you.

**Comment by frohro** [comment]
Thanks Darice,
Your comments on dc_degradation seemed helpful at first.  I am breaking a 25 year simulation into several segments, each with separate utility rates.  I was accommodating the DC degradation by letting later simulations start with lower system capacity to account for that, and then adjusting the insurance rate to adjust for the lower cost that happens because the amount of installed solar is less.  I just wanted to read the dc_degradation, so I didn't have to look it up on SAM and enter it in by hand for each set of simulations I do.  As a work around, I know what it is from SAM, and so I'm assigning it based on what I know it to be, which is kind of what you suggested. However, I don't think this is the real answer to my question, and I think something is still amiss.  The reasons are below.

I am still thing the variable in 100kW_PWWatts.json called "degradation" is really the dc_degradation variable.  It has the correct value in the .json file.  Furthermore, if I assign the degradation to a random number in SAM, and generate a json file for it, degradation changes to that random number in the exported json file.  Also, without it being imported into the simulation, how does the simulation know what the DC degradation is?  It certainly does affect the simulation in precisely the way the DC degradation should, or my code would not work as it is if the PySAM simulations were not using the DC degradation.  I am thinking another work around for this may be to read the variable 'degradation' from the json file, and use that, but I expect that is a mistake, and would just change as soon as it is fixed, and my code would not work then.

Also, as to your comment about pvwattsv5 and pvwattsv7, I am using the 2020.1.17 beta version of SAM, and it says that it is using pvwattsv7, so I don't think that explains the differences between SAM and PySAM.  See the attached screenshot where you can also see how the font size makes the GUI look bad on Ubuntu (just a small annoyance).  I can get around that by reducing the font size in gnome Tweaks, but then the fonts on my other programs are too small.  :-)
![pvwattsv7](https://user-images.githubusercontent.com/994565/75203938-3fda6680-57bb-11ea-9c5b-d1f353dd39ed.png)

Thank you so much for your assistance.  I am very happy for your attention to my problems!

**Comment by frohro** [comment]
Thanks for the encouragement on the tutorials and docs.  I think it will be a good way to accomplish several goals at once, and hopefully help you, the PySAM community and NREL.  Adding to readthedocs seems the right thing to do.  Your video tutorials were helpful for me, and I need to make some for the engineers here, so they can run and modify these simulations in the future as changes occur.  I'll try and make them useful for a more general audience too.

**Comment by cpaulgilman** [comment]
The `degradation` variable is an input to the financial models, which use it to adjust the total annual energy value in kilowatt-hours for cash flow calculations. A performance model like PVWatts runs an hourly or subhourly simulation over one year to calculate a total annual energy value that gets passed to the financial model as the system's output in Year 1. The financial model uses the degradation rate to calculate the annual energy for Years 2 through the analysis period.

In recent versions of SAM, we've added what we call "lifetime" simulations to some performance models so that the performance model simulation runs over the analysis period instead of a single year. That was necessary for a realistic model of battery degradation.  

So, for performance models like pvwattsv7 and pvsamv1 that allow lifetime simulations, degradation is calculated in the performance model instead of the financial model, and for PV systems it is applied on the DC side of the system using the new `dc_degradation` variable. (A similar variable for the generic system model is `generic_degradation`, but is applied on the AC side of the system.)

For pvwattsv7, the `dc_degradation` variable is only required when `system_use_lifetime_output=1`. If `system_use_lifetime_output = 0`, the code sets `dc_degradation` to one.

In the 2020 Beta versions of SAM, we have not enabled lifetime simulations for PVWatts, so the user interface sets `system_use_lifetime_output` to zero, effectively disabling `dc_degradation`. When PVWatts is coupled with a financial model, it applies `degradation`, which is on the Lifetime and Degradation input page. For the performance models that use either `dc_degradation` or `generic_degradation`, the SAM user interface sets `degradation = 1` so that degradation does not get applied by both the performance model and financial model.

So, if you are running pvwattsv7 with `system_use_lifetime_output = 0`, then `dc_degradation` is automatically disabled, and you should either apply the degradation in your own code, or, if you are running a financial model, set the financial model's `degradation` input to the appropriate value.

Whew!

Thanks,
Paul.

**Comment by frohro** [comment]
Wow!  Very helpful explanation, Paul!  Thanks!  

Should I be concerned about the difference between SAM 2020.1.17 and PySAM?  The numbers are 134,380 kWh for SAM's Annual Energy (year 1), and 137,318 kWh for Pysam's pvwattsv7 'Outputs.annual_ac'.  This causes the financial model to give different results too of course.  In other words, does it bother you that I'm getting different answers, even if they are approximately the same?  For my simulations, being this close is okay, but I'm worried that because the numbers don't match that it is an indicator of an error that might be bigger in some case that I'm not using as a test case, and I will give my client wrong information.

I didn't know that PVWattsv7 was able to do the lifetime calculation, basing my understanding on using SAM 2020.1.17, which advertised PVWattsv7.  :-)  

Thanks!

Rob

**Comment by frohro** [comment]
On the degradation issue, your answer leads me to the conclusion, that I didn't want dc_degradation in the first place.  I just want degradation.  I'm sorry for being dense!
Thanks,
Rob

**Comment by dguittet** [comment]
I think they should be matching up.

Have you tried using the Inputs Browser in SAM, accessed via the File dropdown, to compare what the variables are in SAM versus PySAM?

**Comment by frohro** [comment]
Thanks Darice,
With your encouragement that things should equal, I found the problem.  I was looking at the Annual AC system output (kWh) (Outputs.ac_annual) in my python code, and looking at Energy (Outputs.annual_energy) in SAM.  I need to improve the docs in this area.  I forked the repo, and am editing it.  This illustrates one of my problems though.
It is unclear what the difference between these two variables is.  See this screenshot of the docs as they are.
![annual_energy](https://user-images.githubusercontent.com/994565/75727800-97d01a80-5d31-11ea-9039-3546765c71b6.png)
I suspect the larger number (annual_energy) is before some loss, but it isn't before the total loss.  Another place I would go to look is in the SDKTool, but it is similarly unhelpful.
![annual_energy_1](https://user-images.githubusercontent.com/994565/75727968-20e75180-5d32-11ea-9470-c68e2a1cd377.png)
I tried searching the SAM Help, and though I didn't read everything carefully, I didn't find the difference there, either.  We really need a much better way to find out what each variable really is, and to find the variable we want to work with when using PySAM.

Specifically, is there a place where these variables are documented fully, or do I need to go browsing the source code to try and figure out what the difference is between them?

Thanks,
Rob

**Comment by dguittet** [comment]
Apologies for the delay! It's been extremely busy for me these last two weeks.

This [link](https://github.com/NREL/ssc/blob/af28aa8e21eca8496279533af48c7f3c25ebb7e7/ssc/cmod_pvwattsv7.cpp#L1202) takes us to the code showing the difference between `p_ac` (rolled up into `ac_annual`) and `p_gen` (rolled up into `annual_energy`). This shows that the later contains adjustment factors (so optional losses).

A pull request is definitely the way to go. I appreciate you moving through this with perseverance. We know documentation needs to be improved, and your contributions will be helpful.
