### ISSUE TITLE
Pip install causing "SAMNIDIR" error

### ISSUE THREAD

**Issue by ZooBear** [NREL/pysam#56]
Based on [issue 4](https://github.com/NREL/pysam/issues/4) responses, my laptop is a 64-bit machine. I setup a new virtual env for a new project if that might cause the issue. 

Otherwise I get this error.
```
   Complete output (7 lines):
    
Traceback (most recent call last):
      
File "<string>", line 1, in <module>
      
File "C:\\Temp\pip-install-0qja93qc\NREL-PySAM\setup.py", line 24, in <module>
        defaults_dir = os.environ['SAMNTDIR']+"/api/api_autogen/library/defaults/"
      
File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 675, in __getitem__
        raise KeyError(key) from None
    
KeyError: 'SAMNTDIR'

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`
```

**Comment by dguittet** [comment]
Apologies for late response! PySAM isn't set up currently for it to be independently installed using `setup.py install`. This is due to its dependencies on the other SAM repos ([sam](https://github.com/NREL/sam), [ssc](https://github.com/NREL/ssc), etc) which need to be correctly set up on your machine for the PySAM installation to work.

The way to do the `setup.py install` is to have the full [build of SAM](https://github.com/NREL/SAM/wiki), a process which involves setting environment variables such as `SAMNTDIR`. Then you can follow [how to build PySAM](https://github.com/NREL/pysam/wiki/Building,-Packaging-and-Distributing).

**Comment by relativityboy** [comment]
@dguittet [This](https://github.com/NREL/pysam/issues/56#issuecomment-710149418) is valuable info. 

Pysam is not the simplest library. Would be great to have a `contributor_development_environment.md` to help people setup an ideal dev environment where they could run specific unit tests, etc.
